"use strict";

const $ = (id) => document.getElementById(id);
const fmt = (n) => (n >= 1000 ? n.toLocaleString("en-IN") : String(n));
const esc = (s) =>
  String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

function bandClass(b) {
  return b === "high" ? "band-high" : b === "medium" ? "band-medium" : "band-low";
}

async function getJSON(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

async function loadSummary() {
  const s = await getJSON("/api/summary");
  $("c-accounts").textContent = fmt(s.n_accounts);
  $("c-tx").textContent = fmt(s.n_transactions);
  $("c-fraud").textContent = fmt(s.n_fraud);
  $("c-rings").textContent = fmt(s.n_rings);
  $("model-badge").textContent = `model: ${s.model} · fraud rate ${(s.fraud_rate * 100).toFixed(1)}%`;

  if (s.explainer === "openai") {
    const credit = $("footer-credit");
    credit.insertAdjacentHTML(
      "beforeend",
      ' · risk explanations by <a href="https://openai.com/" target="_blank" rel="noopener">OpenAI</a>'
    );
  }

  const select = $("ring-select");
  select.innerHTML = "";
  for (const [id, size] of Object.entries(s.ring_sizes)) {
    const opt = document.createElement("option");
    opt.value = id;
    opt.textContent = `Ring ${id} (${size} accounts)`;
    select.appendChild(opt);
  }
  if (select.options.length) {
    select.value = Object.keys(s.ring_sizes)[0];
    loadRing(select.value);
  }
  select.addEventListener("change", () => loadRing(select.value));
}

async function loadTop() {
  const rows = await getJSON("/api/top?k=50");
  const tbody = $("top-table").querySelector("tbody");
  tbody.innerHTML = "";
  for (const r of rows) {
    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td>${r.rank}</td>
      <td><b>${esc(r.account_id)}</b></td>
      <td>
        <div class="score-cell">
          <div class="score-bar"><span style="width:${(r.risk_score * 100).toFixed(0)}%"></span></div>
          ${r.risk_score.toFixed(3)}
        </div>
      </td>
      <td><span class="band ${bandClass(r.risk_band)}">${r.risk_band}</span></td>
      <td>${r.ring_id >= 0 ? `<span class="tag tag-ring">ring ${r.ring_id}</span>` : "–"}</td>
      <td>${r.true_label ? '<span class="tag tag-fraud">fraud</span>' : "–"}</td>
      <td>${r.degree}</td>`;
    tr.addEventListener("click", () => loadAccount(r.account_id));
    tbody.appendChild(tr);
  }
}

async function loadAccount(accountId) {
  const a = await getJSON(`/api/account/${encodeURIComponent(accountId)}`);
  const d = $("detail");
  const nbrs = a.neighbors
    .map(
      (n) => `
      <div class="row">
        <span class="k">${esc(n.account_id)}</span>
        <span>${n.risk_score.toFixed(3)} <span class="band ${bandClass(n.risk_band)}">${n.risk_band}</span> · rank ${n.rank}</span>
      </div>`
    )
    .join("");
  d.innerHTML = `
    <h3>${esc(a.account_id)}
      <span class="band ${bandClass(a.risk_band)}">${a.risk_band}</span>
      ${a.true_label ? '<span class="tag tag-fraud">fraud label</span>' : ""}
      ${a.ring_id >= 0 ? `<span class="tag tag-ring">ring ${a.ring_id}</span>` : ""}
    </h3>
    <div class="row"><span class="k">Risk score</span><b>${a.risk_score.toFixed(4)}</b></div>
    <div class="row"><span class="k">Risk rank</span><span>${fmt(a.rank)} / ${fmt(parseInt($("c-accounts").textContent.replace(/,/g, ""), 10) || "?")}</span></div>
    <div class="row"><span class="k">Degree</span><span>${fmt(a.degree)} connections</span></div>
    <div class="neighbors">
      <h3>Highest-risk neighbors</h3>
      ${nbrs || '<p class="muted">No neighbors.</p>'}
    </div>
    <div class="explain-box">
      <button id="explain-btn">Explain this account</button>
      <p class="muted" id="explain-text"></p>
    </div>`;
  $("explain-btn").addEventListener("click", async () => {
    const text = $("explain-text");
    text.textContent = "generating explanation…";
    $("explain-btn").disabled = true;
    try {
      const e = await getJSON(`/api/explain/${encodeURIComponent(a.account_id)}`);
      text.textContent = e.explanation;
      if (e.source === "openai") {
        text.insertAdjacentHTML(
          "afterend",
          '<p class="muted source-note">generated by OpenAI</p>'
        );
      }
    } catch (err) {
      text.textContent = `explanation failed: ${err.message}`;
    }
    $("explain-btn").disabled = false;
  });
}

async function loadRing(ringId) {
  const r = await getJSON(`/api/ring/${ringId}`);
  drawRing(r);
  $("ring-list").innerHTML = r.nodes
    .map(
      (n) => `
      <div class="row">
        <b>${esc(n.account_id)}</b>
        ${n.risk_score.toFixed(3)} · <span class="band ${bandClass(n.risk_band)}">${n.risk_band}</span>
        · ext ${n.external_connections}
        ${n.true_label ? '<span class="tag tag-fraud">fraud</span>' : ""}
      </div>`
    )
    .join("");
}

function drawRing(r) {
  const svg = $("ring-svg");
  const cx = 210;
  const cy = 210;
  const radius = 150;
  const n = r.nodes.length;
  const pos = {};
  r.nodes.forEach((node, i) => {
    const angle = (2 * Math.PI * i) / n - Math.PI / 2;
    pos[node.index] = { x: cx + radius * Math.cos(angle), y: cy + radius * Math.sin(angle) };
  });

  let inner = "";
  for (const [a, b] of r.edges) {
    inner += `<line class="edge" x1="${pos[a].x.toFixed(1)}" y1="${pos[a].y.toFixed(1)}" x2="${pos[b].x.toFixed(1)}" y2="${pos[b].y.toFixed(1)}" />`;
  }
  for (const node of r.nodes) {
    const p = pos[node.index];
    const cls = node.true_label ? "node node-fraud" : "node node-clean";
    const r2 = node.risk_score >= 0.7 ? 12 : node.risk_score >= 0.4 ? 9 : 6;
    inner += `<circle class="${cls}" cx="${p.x.toFixed(1)}" cy="${p.y.toFixed(1)}" r="${r2}"><title>${esc(node.account_id)} · ${node.risk_score.toFixed(3)}</title></circle>`;
    inner += `<text x="${p.x.toFixed(1)}" y="${(p.y + 24).toFixed(1)}" text-anchor="middle">${esc(node.account_id.replace("acc_", "a"))}</text>`;
  }
  svg.innerHTML = inner;
}

async function loadDistribution() {
  const dist = await getJSON("/api/distribution?bins=20");
  const canvas = $("dist-chart");
  const ctx = canvas.getContext("2d");
  const dpr = window.devicePixelRatio || 1;
  canvas.width = canvas.clientWidth * dpr;
  canvas.height = 180 * dpr;
  ctx.scale(dpr, dpr);

  const W = canvas.clientWidth;
  const H = 180;
  const max = Math.max(...dist.counts, 1);
  const barW = W / dist.counts.length;
  const margin = 18;

  ctx.clearRect(0, 0, W, H);
  ctx.fillStyle = "#7c8aa0";
  ctx.font = "10px ui-monospace, monospace";
  for (let i = 0; i < dist.counts.length; i++) {
    const h = (dist.counts[i] / max) * (H - margin * 2);
    const x = i * barW;
    const y = H - margin - h;
    ctx.fillStyle = i >= dist.bins.length - 6 ? "#f87171" : "#2dd4bf";
    ctx.fillRect(x + 1, y, barW - 2, h);
    ctx.fillStyle = "#7c8aa0";
    ctx.fillText(String(dist.bins[i]), x + 1, H - 6);
  }
}

loadSummary().catch((e) => console.error(e));
loadTop().catch((e) => console.error(e));
loadDistribution().catch((e) => console.error(e));
